# -*- coding: utf-8 -*-
"""unidad3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_G5e_Du4MKyShUI9BEtfrkEJtGnL04Tr
"""

!pip install git+https://github.com/DLR-RM/rl-baselines3-zoo
!apt-get install swig cmake ffmpeg
!pip install gymnasium[atari]
!pip install gymnasium[accept-rom-license]
!apt install python-opengl
!apt install xvfb
!pip3 install pyvirtualdisplay
# Virtual display
from pyvirtualdisplay import Display
virtual_display = Display(visible=0, size=(1400, 900))
virtual_display.start()

!python -m rl_zoo3.train --algo dqn  --env SpaceInvadersNoFrameskip-v4 -f logs/ -c dqn.yml